import logging
import uuid
from typing import Any

from google.adk.events import Event, EventActions
from google.adk.sessions import BaseSessionService, DatabaseSessionService, Session

from common.config import SETTINGS
from common.constants import APP_NAME, SESSION_TITLE_KEY, SYSTEM_AUTHOR, USER_AUTHOR
from data_agent.schemas import (
    SessionInfo, ListSessionsResponse, CreateSessionResponse, RenameSessionRequest, CreateSessionTitleResponse
)
from data_agent.services.session_guard import SessionBusyError, SessionGuard
from data_agent.services.system_runner import SystemRunner
from data_agent.utils import convert_unix_to_datetime

logger = logging.getLogger(__name__)

# Seconds a title write waits for an in-flight run to release the session guard.
SESSION_WRITE_TIMEOUT = 60.0
STALE_SESSION_ATTEMPTS = 3
STALE_SESSION_MARKER = "has been modified in storage"


class SessionNotReadyError(RuntimeError):
    """Raised when a session cannot be titled yet because no user message reached storage."""


def _is_stale_session_error(error: Exception) -> bool:
    return STALE_SESSION_MARKER in str(error)


def create_session_store() -> DatabaseSessionService:
    db_url = f"{SETTINGS.session_db.host}:{SETTINGS.session_db.port}/{SETTINGS.session_db.name}"
    return DatabaseSessionService(db_url=f"postgresql+asyncpg://postgres@{db_url}")


class DBSessionService:
    def __init__(
            self,
            session_service: BaseSessionService,
            system_runner: SystemRunner,
            session_guard: SessionGuard
    ):
        self._session_service = session_service
        self._system_runner = system_runner
        self._session_guard = session_guard
        self._app_name = APP_NAME

    @staticmethod
    def _find_last_user_message(session: Session) -> str | None:
        for event in reversed(session.events):
            if event.author != USER_AUTHOR or not event.content or not event.content.parts:
                continue

            for part in reversed(event.content.parts):
                if part.text and part.text.strip():
                    return part.text

        return None

    async def _load_session(self, user_id: str, session_id: str) -> Session:
        session = await self._session_service.get_session(
            app_name=self._app_name,
            user_id=user_id,
            session_id=session_id
        )
        if not session:
            raise ValueError(f"User {user_id} does not have session {session_id}")

        return session

    async def _append_state_delta(
            self,
            user_id: str,
            session_id: str,
            state_delta: dict[str, Any],
            skip_if_set: str | None = None
    ) -> dict[str, Any]:
        """Append a state change, reloading the session immediately before the write.

        Loading right before ``append_event`` keeps the window in which the session
        can go stale down to a single round trip; the retry then covers the writers
        the in-process guard cannot serialise. When ``skip_if_set`` names a state key
        the reloaded session already carries, the write is dropped -- that is how a
        title generated by a caller that lost the race stops overwriting the winner.

        Returns the state now in force for the keys of ``state_delta``.
        """
        for attempt in range(1, STALE_SESSION_ATTEMPTS + 1):
            session = await self._load_session(user_id, session_id)

            if skip_if_set and session.state.get(skip_if_set):
                logger.info(f"Session {session_id} of user {user_id} already has {skip_if_set}, skipping the write")
                return {key: session.state.get(key) for key in state_delta}

            event = Event(author=SYSTEM_AUTHOR, actions=EventActions(state_delta=state_delta))
            try:
                await self._session_service.append_event(session, event)
                return dict(state_delta)
            except ValueError as e:
                if attempt == STALE_SESSION_ATTEMPTS or not _is_stale_session_error(e):
                    raise

                logger.warning(
                    f"Session {session_id} of user {user_id} went stale on attempt {attempt}, reloading and retrying"
                )

    async def list_sessions(self, user_id: str) -> ListSessionsResponse:
        try:
            result = await self._session_service.list_sessions(app_name=self._app_name, user_id=user_id)

            sessions = []
            for session in result.sessions:
                sessions.append(
                    SessionInfo(
                        session_id=session.id,
                        app_name=session.app_name,
                        user_id=session.user_id,
                        state=session.state,
                        events=session.events,
                        last_update_time=convert_unix_to_datetime(session.last_update_time)
                    )
                )

            logger.info(f"Retrieved session list of user {user_id}: {[session.session_id for session in sessions]}")
            return ListSessionsResponse(sessions=sessions)
        except Exception as e:
            logger.exception(f"Failed to list sessions of user {user_id}: {str(e)}")
            raise

    async def create_session(self, user_id: str) -> CreateSessionResponse:
        try:
            session = await self._session_service.create_session(
                app_name=self._app_name,
                user_id=user_id,
                session_id=uuid.uuid4().hex
            )

            logger.info(f"Created session for user {user_id} with id: {session.id}")
            return CreateSessionResponse(session_id=session.id)
        except Exception as e:
            logger.exception(f"Failed to create new session for user {user_id}: {str(e)}")
            raise

    async def _create_session_title(
            self,
            user_id: str,
            session_id: str,
            guard_timeout: float | None
    ) -> CreateSessionTitleResponse:
        session = await self._load_session(user_id, session_id)

        session_title = session.state.get(SESSION_TITLE_KEY)
        if session_title:
            return CreateSessionTitleResponse(session_title=session_title)

        user_message = self._find_last_user_message(session)
        if not user_message:
            raise SessionNotReadyError(
                f"Cannot create session title: session {session_id} has no user message yet"
            )

        session_title = await self._system_runner.create_session_title(
            user_id=user_id,
            session_id=session_id,
            user_message=user_message
        )

        async with self._session_guard.hold(session_id, timeout=guard_timeout):
            state = await self._append_state_delta(
                user_id=user_id,
                session_id=session_id,
                state_delta={SESSION_TITLE_KEY: session_title},
                skip_if_set=SESSION_TITLE_KEY
            )

        logger.info(f"Created a title {state[SESSION_TITLE_KEY]} for session {session_id} of user {user_id}")
        return CreateSessionTitleResponse(session_title=state[SESSION_TITLE_KEY])

    async def create_session_title(self, user_id: str, session_id: str) -> CreateSessionTitleResponse:
        """Title a session on request.

        Clients poll this while a session is untitled, so it has to be cheap and safe
        to repeat: an already titled session returns the stored title without calling
        the model, and a session a run is holding is reported busy rather than
        written to, because the write would invalidate the run.
        """
        try:
            if self._session_guard.is_busy(session_id):
                raise SessionBusyError(f"Session {session_id} is being written by a run")

            return await self._create_session_title(user_id, session_id, guard_timeout=SESSION_WRITE_TIMEOUT)
        except (SessionBusyError, SessionNotReadyError) as e:
            logger.info(f"Postponed the title for session {session_id} of user {user_id}: {str(e)}")
            raise
        except Exception as e:
            logger.exception(f"Failed to create a title for session {session_id} of user {user_id}: {str(e)}")
            raise

    async def ensure_session_title(self, user_id: str, session_id: str):
        """Title a session once its run finished, so the client never has to ask.

        Runs in the background after the run released the session guard, which is what
        keeps this write from invalidating the ``Session`` the run was holding. Every
        failure is logged and dropped -- the client's polling stays as the fallback.
        """
        try:
            await self._create_session_title(user_id, session_id, guard_timeout=None)
        except Exception as e:
            logger.warning(f"Could not title session {session_id} of user {user_id} after its run: {str(e)}")

    async def rename_session_title(self, user_id: str, session_id: str, request: RenameSessionRequest):
        try:
            async with self._session_guard.hold(session_id, timeout=SESSION_WRITE_TIMEOUT):
                await self._append_state_delta(
                    user_id=user_id,
                    session_id=session_id,
                    state_delta={SESSION_TITLE_KEY: request.session_title}
                )

            logger.info(f"Renamed session {session_id} of user {user_id} to {request.session_title}")
        except SessionBusyError as e:
            logger.info(f"Could not rename session {session_id} of user {user_id}: {str(e)}")
            raise
        except Exception as e:
            logger.exception(f"Failed to rename the session {session_id} to {request.session_title}: {str(e)}")
            raise

    async def get_session(self, user_id: str, session_id: str) -> SessionInfo:
        try:
            session = await self._load_session(user_id, session_id)

            for event in session.events:
                event.timestamp = convert_unix_to_datetime(event.timestamp)

            logger.info(f"Retrieved {session_id} session info of user {user_id}")
            return SessionInfo(
                session_id=session.id,
                app_name=session.app_name,
                user_id=session.user_id,
                state=session.state,
                events=session.events,
                last_update_time=convert_unix_to_datetime(session.last_update_time)
            )
        except Exception as e:
            logger.exception(f"Failed to get session {session_id} of user {user_id}: {str(e)}")
            raise

    async def delete_session(self, user_id: str, session_id: str):
        try:
            await self._session_service.delete_session(
                app_name=self._app_name,
                user_id=user_id,
                session_id=session_id
            )

            logger.info(f"Deleted {session_id} session of user {user_id}")
        except Exception as e:
            logger.exception(f"Failed to delete session {session_id} of user {user_id}: {str(e)}")
            raise
